FROM ubuntu

# Update package lists
RUN apt-get update

# Install Python and pip
RUN apt-get install -y python3 python3-pip

# Set the default Python version
RUN ln -s /usr/bin/python3 /usr/bin/python


